// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMI.Shared.Models;

public partial class Persona
{
    public int id { get; set; }

    public int? id_Genero { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }
}